set a fail if cache is not valid

diff --git a/.github/workflows/obsidian-plugin-bump-version.yaml b/.github/workflows/obsidian-plugin-bump-version.yaml
--- a/.github/workflows/obsidian-plugin-bump-version.yaml
+++ b/.github/workflows/obsidian-plugin-bump-version.yaml
@@ -65,6 +65,11 @@ jobs:
 
     runs-on: ubuntu-latest
     steps:
+      - name: Verify Inputs for cache
+        if: ${{ inputs.CACHE != 'npm' && inputs.CACHE != 'pnpm' && inputs.CACHE != 'yarn' }}
+        run: |
+          echo "::error::CACHE must be one of npm, pnpm or yarn"
+          exit 1
       - name: rename submodule env
         if: ${{ inputs.SUBMODULE}}
         run: |
@@ -176,6 +181,11 @@ jobs:
       VERSION: ""
     runs-on: ubuntu-latest
     steps:
+      - name: Verify inputs for cache
+        if: ${{ inputs.CACHE != 'npm' && inputs.CACHE != 'pnpm' && inputs.CACHE != 'yarn' }}
+        run: |
+          echo "::error::CACHE must be one of npm, pnpm or yarn"
+          exit 1
       - name: rename submodule env
         if: ${{ inputs.SUBMODULE}}
         run: |
diff --git a/.github/workflows/obsidian-plugin-release.yaml b/.github/workflows/obsidian-plugin-release.yaml
--- a/.github/workflows/obsidian-plugin-release.yaml
+++ b/.github/workflows/obsidian-plugin-release.yaml
@@ -49,6 +49,11 @@ jobs:
       SUBMODULE: ${{ inputs.SUBMODULE }}
       VERSION: ""
     steps:
+      - name: verify inputs
+        if: ${{ inputs.CACHE != 'npm' && inputs.CACHE != 'pnpm' && inputs.CACHE != 'yarn' }}
+        run: |
+          echo "::error::CACHE must be one of npm, pnpm or yarn"
+          exit 1
       - name: Set to recursive
         if: ${{ inputs.SUBMODULE }}
         run: |
